[build]
  command = "npm run build"
  publish = ".next"
  functions = "api"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-svelte"
  [plugins.inputs]
    entryFile = "sveltekit/src/main.js"