import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import Intro from '@/components/layout/Intro';
import UnderConstruction from '@/components/layout/UnderConstruction';
import HamburgerMenu from '../components/HamburgerMenu/HamburgerMenu';
export default function Home() {
	return (
		<>
			<HamburgerMenu />
			<UnderConstruction />
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon/favicon.ico' />
			</Head>
			<main className='homepage'>
				<Intro />
			</main>
		</>
	);
}
